###########################################################
#                                                         #
# This package contains the components and sensors I use  #
# to monitor the Homeassistant software and system itself #
#                                                         #
###########################################################
recorder:
  purge_interval: 1
  purge_keep_days: 7
  db_url: !secret mariadb_url

logbook: !include ../../extras/includes/logging.yaml

history: !include ../../extras/includes/logging.yaml

logger:
  default: info
#  logs:
#    homeassistant.components.component: info

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /config
      - type: memory_use_percent
      - type: last_boot
      - type: processor_use

automation:
  - alias: Device - Power on
    initial_state: on
    trigger:
      platform: homeassistant
      event: start
    condition:
      - condition: state
        entity_id: input_boolean.maintenance_mode
        state: 'off'
    action:
      service: script.notify
      data:
        call_power_on: 1
        tell: matt
  
